# Practice in training with 2D arrays

## Plane orientation

### De facto the same for every Python algorith:
<img src="Python_Array_Indexing_Orientation_Plane.png" width="400">


### At your own will:
<img src="Python_&_Physical_Orientation_Plane.png" width="900">

## Note: 
1) The defining point in your algorithm regarding the physical domain orientation and its correspondence to the Python domain is when you first initialise your unknown variables, i.e. if you would go numpy.ones((ny, nx)) **or** numpy.ones((nx, ny)).

2) The point where you will need to be extra carefull in your algorithm is when applying the BC, which will define how your physical problem will behave.

3) You will still work with 1-dimensional grid arrays (i.e. x,y,dx,dy) in your code, but when would need to plot contours, for instance, then you are going to need the 2-dimensional arrays.

## ------------------------ Hands-on example ------------------------

Here we are going to keep the first orientation, i.e. [ny, nx]

In [5]:
#---------- Import libraries ----------

import numpy as np
import matplotlib.pyplot as plt

In [29]:
#---------- Set-up ----------

# Define number of points
nx = 6
ny = 6

# Define grid resolution
dx = .5
dy = .5

# Initialise array
temp = np.ones((ny, nx))
print(temp)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


## Basic operations implementation

### Compute with 1st order forwards :
## $
\begin{equation}
\frac{\partial (temp)}{\partial x} 
\end{equation}
$  and $
\begin{equation}
\frac{\partial (temp)}{\partial y} 
\end{equation}
$ 



In [30]:
# Compute x-gradient
grad_x = (temp[1:-1, 1:] - temp[1:-1, :-1]) / dx

# Compute y-gradient
grad_y = (temp[:-1, 1:-1] - temp[1:, 1:-1]) / dy

print(grad_x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## BC implementation

$$\begin{equation} temp(x=0,y,t) = 2 \; \end{equation} \;\;\;\;\;\; (Dirichlet \; BC) $$ 

$$\begin{equation} \frac{\partial temp}{\partial x}(x=L,y,t) = 0 \; \end{equation} \;\;\; (Neumann \; BC) $$ 

$$\begin{equation} temp(x,y=0,t) = 0 \; \end{equation} \;\;\;\;\;\; (Dirichlet \; BC) $$ 

$$\begin{equation} \frac{\partial temp}{\partial y}(x,y=L,t) = 1 \; \end{equation} \;\;\; (Neumann \; BC) $$

In [31]:
# BC West & East
temp[:,0] = 2
temp[:,-1] = temp[:, -2]
# BC South & North
temp[-1, :] = 0
temp[0, :] = temp[0, :] -1 *dy

print(temp)

[[1.5 0.5 0.5 0.5 0.5 0.5]
 [2.  1.  1.  1.  1.  1. ]
 [2.  1.  1.  1.  1.  1. ]
 [2.  1.  1.  1.  1.  1. ]
 [2.  1.  1.  1.  1.  1. ]
 [0.  0.  0.  0.  0.  0. ]]


## RHS augmentation of 2D array

In [35]:
# Initialise a "RHS" array
rhs     = numpy.ones((ny,nx)) * 10
rhs_int = numpy.copy(rhs[1:-1,1:-1])
print(rhs_int)

[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]


In [36]:
# BC West & East
patch_west = np.zeros((ny-2, 1))
patch_east = np.zeros((ny-2, 1))

print('West:')
print(patch_west)
print()
print('East:')
print(patch_east)
print()
print()

# Assemble the augmented RHS array in x-direction
rhs_augm_x = np.concatenate((patch_west, rhs_int, patch_east), axis = 1)

print('Completed x direction:')
print(rhs_augm_x)

West:
[[0.]
 [0.]
 [0.]
 [0.]]

East:
[[0.]
 [0.]
 [0.]
 [0.]]


Completed x direction:
[[ 0. 10. 10. 10. 10.  0.]
 [ 0. 10. 10. 10. 10.  0.]
 [ 0. 10. 10. 10. 10.  0.]
 [ 0. 10. 10. 10. 10.  0.]]


In [40]:
# BC South & North
patch_south = np.zeros((1, nx))
patch_north = np.zeros((1, nx))


print('North:')
print(patch_north)
print()
print('South:')
print(patch_south)
print()
print()

# Assemble the augmented RHS array in both x-direction and y-direction
rhs_augm = np.concatenate((patch_north, rhs_augm_x, patch_south), axis = 0)

print('Completed both x and y directions:')
print(rhs_augm)

North:
[[0. 0. 0. 0. 0. 0.]]

South:
[[0. 0. 0. 0. 0. 0.]]


Completed both x and y directions:
[[ 0.  0.  0.  0.  0.  0.]
 [ 0. 10. 10. 10. 10.  0.]
 [ 0. 10. 10. 10. 10.  0.]
 [ 0. 10. 10. 10. 10.  0.]
 [ 0. 10. 10. 10. 10.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


### Side note:
There are some built-in Python commands (e.g. numpy.concatenate) where you need to specify the axis in which you want a specific operation to be performed.

<img src="Python_axes_enumeration.png" width="500">